apiVersion: v1
name: contour
description: Contour Ingress controller for Kubernetes
version: 2.3.5
appVersion: 1.10.0
keywords:
  - ingress
  - envoy
  - contour
home: https://github.com/bitnami/charts/tree/master/bitnami/contour
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
sources:
  - https://github.com/projectcontour/contour
  - https://github.com/envoyproxy/envoy
  - https://github.com/bitnami/bitnami-docker-contour
  - https://projectcontour.io
maintainers:
  - name: cellebyte
    url: https://github.com/Cellebyte
  - name: Bitnami
    email: containers@bitnami.com
annotations:
  category: Infrastructure
